package ru.xataaa.torrentbot.file;

public enum DownloadFileStatus {
    DISCOVERED,
    READY_TO_UPLOAD,
    UPLOADING,
    UPLOADING_TO_S3,
    UPLOADED,
    S3_UPLOADED,
    DOWNLOAD_LINK_CREATED,
    UNKNOWN_UPLOAD_RESULT,
    UPLOAD_FAILED_RETRYABLE,
    UPLOAD_FAILED_FINAL,
    SKIPPED_TOO_LARGE,
    SKIPPED_UNSUPPORTED,
    SKIPPED_BY_USER,
    DELETE_PENDING,
    DELETING,
    DELETED,
    DELETE_FAILED_RETRYABLE,
    DELETE_FAILED_FINAL
}
