package ru.xataaa.torrentbot.job;

public enum DownloadJobStatus {
    QUEUED,
    CREATED,
    ADDING_TO_QBITTORRENT,
    ADDED_TO_QBITTORRENT,
    WAITING_METADATA,
    DOWNLOADING,
    PAUSED_BY_USER,
    DOWNLOAD_COMPLETED,
    DISCOVERING_FILES,
    WAITING_FILE_SELECTION,
    DELIVERY_PENDING,
    UPLOADING_TO_TELEGRAM,
    DELIVERY_COMPLETED,
    CLEANUP_PENDING,
    CLEANING_UP,
    CLEANUP_COMPLETED,
    FINISHED,
    RETRY_WAITING,
    FAILED_RECOVERABLE,
    FAILED_FINAL
}
