package ru.xataaa.torrentbot.common;

public enum ErrorCode {
    QBITTORRENT_UNAVAILABLE,
    QBITTORRENT_AUTH_FAILED,
    QBITTORRENT_ADD_FAILED,
    QBITTORRENT_METADATA_TIMEOUT,
    QBITTORRENT_DOWNLOAD_TIMEOUT,
    QBITTORRENT_FILES_NOT_FOUND,
    TELEGRAM_SEND_FAILED,
    TELEGRAM_UPLOAD_FAILED,
    TELEGRAM_UPLOAD_UNKNOWN_RESULT,
    S3_UPLOAD_FAILED,
    S3_UNAVAILABLE,
    S3_DELETE_FAILED,
    FILE_NOT_FOUND,
    FILE_TOO_LARGE,
    INSUFFICIENT_DISK_SPACE,
    UNSUPPORTED_FILE_TYPE,
    INVALID_MAGNET,
    ACCESS_DENIED,
    CLEANUP_FAILED,
    JOB_TIMEOUT,
    UNKNOWN_ERROR
}
